import type { Echo } from "./types";

/** Gainesville, GA center + nearby points + a few global landmarks for map demo */
export const DEFAULT_CENTER = { lat: 34.1973, lng: -83.1199 };

export const SEED_ECHOES: Echo[] = [
  {
    id: "seed_downtown_quiet",
    creatorId: "seed_curator",
    creatorName: "City Archive",
    displayMode: "verified",
    lat: 34.1979,
    lng: -83.1192,
    contentType: "text",
    text: "Stand still for ten seconds. The brick remembers every market day since 1821.",
    moodTags: ["history", "quiet"],
    qualityScore: 9.1,
    visibility: "public",
    createdAt: "2025-11-12T14:22:00.000Z",
    isSeed: true,
    placeLabel: "Downtown Square",
    discoveredCount: 1842,
  },
  {
    id: "seed_bridge_confession",
    creatorId: "seed_anon_12",
    creatorName: "river_walker",
    displayMode: "pseudonym",
    lat: 34.1958,
    lng: -83.1175,
    contentType: "text",
    text: "I almost left this town. Then the light hit the water just right. I stayed.",
    moodTags: ["confession", "hope"],
    qualityScore: 8.7,
    visibility: "public",
    createdAt: "2026-03-02T21:08:00.000Z",
    isSeed: true,
    placeLabel: "River bridge",
    discoveredCount: 903,
  },
  {
    id: "seed_coffee_tip",
    creatorId: "seed_local_3",
    creatorName: "amber_hours",
    displayMode: "pseudonym",
    lat: 34.1991,
    lng: -83.1221,
    contentType: "text",
    text: "Order the cold brew after 3pm. They pull a quieter roast and the patio faces west.",
    moodTags: ["tip"],
    qualityScore: 8.2,
    visibility: "public",
    createdAt: "2026-06-18T16:40:00.000Z",
    isSeed: true,
    placeLabel: "Main St café strip",
    discoveredCount: 612,
    cycle: {
      id: "cycle_coffee",
      title: "Best cold brew window",
      hypothesis: "Afternoon pours taste cleaner than morning rushes.",
      outcome: "Blind preference 18/24 for 3–5pm pours on weekdays.",
      confidence: 78,
      metrics: [
        { label: "Samples", value: 24 },
        { label: "Preference rate", value: 75, unit: "%" },
        { label: "Avg wait", value: 4.2, unit: "min" },
      ],
      notes: "Weekend brunch crowds reverse the effect.",
    },
  },
  {
    id: "seed_poetry_park",
    creatorId: "seed_poet",
    creatorName: "dusk_ink",
    displayMode: "pseudonym",
    lat: 34.2012,
    lng: -83.1158,
    contentType: "text",
    text: "Soft grass. Soft sky.\nSomeone laughed two benches over.\nThe city exhaled.",
    moodTags: ["poetry", "wonder"],
    qualityScore: 9.0,
    visibility: "public",
    createdAt: "2026-04-09T19:15:00.000Z",
    isSeed: true,
    placeLabel: "Memorial Park",
    discoveredCount: 1404,
  },
  {
    id: "seed_trail_warning",
    creatorId: "seed_hiker",
    creatorName: "Anonymous",
    displayMode: "anonymous",
    lat: 34.1924,
    lng: -83.1268,
    contentType: "text",
    text: "After rain, the last switchback gets slick. Use the right-hand rail.",
    moodTags: ["warning", "tip"],
    qualityScore: 8.5,
    visibility: "public",
    createdAt: "2026-02-21T11:02:00.000Z",
    isSeed: true,
    placeLabel: "Greenway trailhead",
    discoveredCount: 477,
  },
  {
    id: "seed_future_msg",
    creatorId: "seed_future",
    creatorName: "time_capsule",
    displayMode: "pseudonym",
    lat: 34.1965,
    lng: -83.1215,
    contentType: "text",
    text: "If you are reading this in 2030: the oak by the library was still here. Hug it for me.",
    moodTags: ["hope", "quiet"],
    qualityScore: 8.9,
    visibility: "public",
    createdAt: "2026-01-01T00:05:00.000Z",
    isSeed: true,
    placeLabel: "Library lawn",
    discoveredCount: 2201,
  },
  {
    id: "seed_campus_data",
    creatorId: "seed_researcher",
    creatorName: "field_notes",
    displayMode: "verified",
    lat: 34.2045,
    lng: -83.1132,
    contentType: "hybrid",
    text: "Foot traffic peaks at 12:40. Sit facing south if you want sun without glare.",
    moodTags: ["data", "tip"],
    qualityScore: 8.4,
    visibility: "public",
    createdAt: "2026-05-14T12:50:00.000Z",
    isSeed: true,
    placeLabel: "Campus quad",
    discoveredCount: 331,
    cycle: {
      id: "cycle_quad",
      title: "Quad occupancy cycle",
      hypothesis: "Midday sun + class change = densest social layer.",
      outcome: "Peak density 12:35–12:55; best conversational ambient noise at 0.7 relative.",
      confidence: 86,
      metrics: [
        { label: "Peak people", value: 142 },
        { label: "Peak window", value: "20 min" },
        { label: "Noise score", value: 0.7 },
        { label: "Days sampled", value: 11 },
      ],
    },
  },
  {
    id: "seed_night_wonder",
    creatorId: "seed_stargazer",
    creatorName: "north_porch",
    displayMode: "pseudonym",
    lat: 34.1899,
    lng: -83.1095,
    contentType: "text",
    text: "On clear nights look just above the water tower. The Milky Way still leaks through.",
    moodTags: ["wonder", "tip"],
    qualityScore: 9.2,
    visibility: "public",
    createdAt: "2025-09-30T23:40:00.000Z",
    isSeed: true,
    placeLabel: "Overlook ridge",
    discoveredCount: 768,
  },
  // A couple farther seed echoes for map richness
  {
    id: "seed_atl_peachtree",
    creatorId: "seed_atl",
    creatorName: "metro_memory",
    displayMode: "verified",
    lat: 33.759,
    lng: -84.388,
    contentType: "text",
    text: "Peachtree does not end. It only changes its mind.",
    moodTags: ["history", "poetry"],
    qualityScore: 8.6,
    visibility: "public",
    createdAt: "2026-07-01T18:00:00.000Z",
    isSeed: true,
    placeLabel: "Atlanta — Midtown",
    discoveredCount: 5102,
  },
  {
    id: "seed_savannah_oak",
    creatorId: "seed_sav",
    creatorName: "moss_keeper",
    displayMode: "pseudonym",
    lat: 32.0759,
    lng: -81.0883,
    contentType: "text",
    text: "Spanish moss is not a parasite. It is a guest that learned to float.",
    moodTags: ["history", "wonder"],
    qualityScore: 8.8,
    visibility: "public",
    createdAt: "2026-04-22T10:12:00.000Z",
    isSeed: true,
    placeLabel: "Savannah square",
    discoveredCount: 2890,
  },
];

export const MOOD_LABELS: Record<string, string> = {
  wonder: "Wonder",
  confession: "Confession",
  tip: "Tip",
  history: "History",
  quiet: "Quiet",
  hope: "Hope",
  warning: "Warning",
  poetry: "Poetry",
  data: "Data",
};
